# Generated by Django 5.0.6 on 2024-05-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('stock', models.IntegerField()),
                ('presentacion', models.CharField(choices=[('1', 'Caja'), ('2', 'Pieza'), ('3', 'Paquete')], max_length=1, verbose_name='Presentación')),
            ],
        ),
    ]
