# Generated by Django 5.0.6 on 2024-05-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('clave', models.IntegerField(default=0, null=True)),
                ('variable', models.CharField(choices=[('1', 'Temperatura Ambiente'), ('2', 'Humedad Relativa'), ('3', 'Presion Barometrica'), ('4', 'Velocidad y Direccion del viento'), ('5', 'Radiacion solar'), ('6', 'Indice uv')], max_length=1, verbose_name='Presentación')),
            ],
        ),
        migrations.DeleteModel(
            name='Variables',
        ),
    ]
