# Generated by Django 5.0.6 on 2024-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_usuarios_delete_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='variable',
            field=models.CharField(choices=[('1', 'Temperatura Ambiente'), ('2', 'Humedad Relativa'), ('3', 'Presion Barometrica'), ('4', 'Velocidad y Direccion del viento'), ('5', 'Radiacion solar'), ('6', 'Indice uv')], max_length=1, verbose_name='Holi'),
        ),
    ]
