version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: diplomas-upn
    #restart: always
    depends_on:
      - db-estacion
    ports:
      - 8000:8000
      # - 80:80
    volumes:
      - ./app/estacion/:/app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}

  db-estacion:
    image: mariadb
    container_name: estacion-db
    #restart: always
    environment:
      MYSQL_DATABASE: estacion
      MYSQL_USER: estacion_user
      MYSQL_PASSWORD: 123Alcala
      MYSQL_ROOT_PASSWORD: admin1234
    volumes:
      - db-estacion:/var/lib/mysql
    ports:
      - 3320:3306

volumes:
  db-estacion:
